"""added page_data to engagement

Revision ID: 360d3842a325
Revises: c77154d1e83e
Create Date: 2025-09-12 15:30:18.672967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '360d3842a325'
down_revision: Union[str, None] = 'c77154d1e83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discoveryagentmodel')
    op.drop_table('exploitagentmodel')
    op.add_column('pentestengagement', sa.Column('page_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pentestengagement', 'page_data')
    op.create_table('exploitagentmodel',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('agent_status', sa.VARCHAR(), nullable=False),
    sa.Column('max_steps', sa.INTEGER(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('model_costs', sa.FLOAT(), nullable=True),
    sa.Column('log_filepath', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), nullable=False),
    sa.Column('opik_prompt_name', sa.VARCHAR(), nullable=True),
    sa.Column('opik_prompt_commit', sa.VARCHAR(), nullable=True),
    sa.Column('vulnerability_title', sa.VARCHAR(), nullable=False),
    sa.Column('agent_steps_data', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discoveryagentmodel',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('agent_status', sa.VARCHAR(), nullable=False),
    sa.Column('max_steps', sa.INTEGER(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('model_costs', sa.FLOAT(), nullable=True),
    sa.Column('log_filepath', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), nullable=False),
    sa.Column('opik_prompt_name', sa.VARCHAR(), nullable=True),
    sa.Column('opik_prompt_commit', sa.VARCHAR(), nullable=True),
    sa.Column('agent_steps_data', sqlite.JSON(), nullable=True),
    sa.Column('page_data', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
