"""added agent_approval_payload

Revision ID: 72404a86afc6
Revises: 9a3505b17b53
Create Date: 2025-09-16 13:32:59.466062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72404a86afc6'
down_revision: Union[str, None] = '9a3505b17b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exploitagent', sa.Column('approval_payload_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exploitagent', 'approval_payload_data')
    # ### end Alembic commands ###
