"""added complete_data

Revision ID: c67200a074fe
Revises: 5bc9a87825f7
Create Date: 2025-09-27 17:16:28.011219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c67200a074fe'
down_revision: Union[str, None] = '5bc9a87825f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exploitagent', sa.Column('complete_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exploitagent', 'complete_data')
    # ### end Alembic commands ###
